### ISSUE TITLE
2018-04-07

### ISSUE THREAD

**Issue by CoolTomatos** [CoolTomatos/GuaPi-CG-Study-Group#1]
---

# 晚饭买菜
@Falke117  付了10.54
@chenyizi086 付了12.00
均摊下来每人5.64

---

# 晚上喝酒
账单如下：

| Amount | Item           | Price |
| ------ | :------------: | ----: |
| 2      | Bags of Fries  | 9.00  |
| 3      | White Tequila  | 12.00 |
| 2      | Rochefort 8    | 12.50 |
| 1      | Duvel 25cl     | 3.95  |
| 2      | Hoe. Radler    | 7.00  |
| 1      | De Knoinck     | 3.95  |
| 1      | Rochefort 6    | 5.50  |
| 1      | Hoe. Wit       | 3.00  |
| 1      | Orval Trappist | 6.25  |
| -      | 合计           | 63.15 |

应付款：
- @Falke117 ：19.50
- @Zcalory ：17.20
- @chenyizi086 ：7.95
- @CoolTomatos ： 18.50
---

**Comment by Falke117** [comment]
@CoolTomatos  Send via N28

**Comment by Falke117** [comment]
10.54 for bean sprouts, pork and noddle

**Comment by CoolTomatos** [comment]
@Falke117
晚上吃饭所有一共花的钱10.54还是有另一部分菜不是你买的？

**Comment by Falke117** [comment]
> 另一部分菜不是你买的？

Ez bought some from Jumbo as well.

**Comment by CoolTomatos** [comment]
最终结算：
@Zcalory 付3.31给 @Falke117 ，19.53给 @CoolTomatos
@chenyizi086 付1.59给 @Falke117

**Comment by Zcalory** [comment]
Done.

**Comment by CoolTomatos** [comment]
@Falke117 你收起了就把issue关掉吧。
我这边已经收起了。

**Comment by Falke117** [comment]
Case closed
